.github/workflows/ci.yaml, Dockerfile, dataplane/Dockerfile, main.go
One workflow with three jobs will be in place: 
- A changeset job that gathers the list of changes in the commit.
- A PR job: this will get triggered when someone opens a PR. Images will be built and added as job artifacts (so they don't stick around forever and consume metered space in GHCR). 
- A `main` branch job: this will get triggered when commits are pushed to `main` (either from a push, or a PR is merged). Images will be built and pushed to GHCR. 
Both jobs utilize Docker build caching through the use of the `cache-from` and `cache-to` fields in the Docker build steps. 
The jobs execute conditionally. The first main condition (as noted in the bullets above) is the event type that triggered the action. The next condition (or group of conditions really) tests whether or not to run …
=> chore: add a cI system to build images

dataplane/README.md, dataplane/main.go, dataplane/xdp.c, go.mod
Try and ensure XDP redirect will work in KIND
This Updates the XDP program to rewrite:
- Src Mac address
- Dst Port
and allows us to configure if we want to run cksum
calculation on a per backend basis. It also fixes
the existing CKSUM calculation function to ignore
trailing bits.
Lastly We should be using the autogenerated bpf2go
map structs from `bpf_*.go`
For running in KIND make sure to turn ON GRO manually, and if using cksums (I wouldn't) turn off CKSUM offloading
=> Fix XDP redirect in kind

dataplane/Cargo.toml, dataplane/controllers/udproute/Cargo.toml, dataplane/controllers/udproute/src/main.rs
This patch simply adds the skeleton for a `UDPRoute` controller.
=> chore: add template for udproute controller

controllers/gateway_controller.go
Filter out Gateways before reconciliation
Fixes: #17
=> feat: filter out Gateways before reconciliation

.github/workflows/lint.yaml, .github/workflows/test.yaml, Dockerfile, controllers/gateway_controller.go, controllers/gateway_controller_test.go, controllers/gatewayclass_controller.go, go.mod, go.sum, internal/test/utils/utils.go, pkg/vars/vars.go, test/integration/suite_test.go
This PR includes a fix for our `GatewayClass` watch predicate, adds some testing utilities for unit testing reconcilers and adds unit tests for the Gateway controllers `gatewayHasMatchingGatewayClass` watch predicate.
Additionally this adds CI workflows for automatically running lint and unit tests on every PR.
Resolves #17
=> add ci linting and tests

.github/workflows/lint.yaml
Fix `golangci-lint` timeout via GitHub Actions workflow.
The default timeout is at 1 minute. Increasing the timeout should keep the workflow going until completed. May need to adjust as the code base gets larger.
Fixes https://github.com/Kong/blixt/issues/27
Signed-off-by: Antonette Caldwell <pullmana8@gmail.com>
=> Increase golangci-lint timeout

dataplane/Dockerfile
Adds `protoc` to the build phase for building the dataplane image as needed for the new Rust based dataplane.
=> fix: add protoc to rust build

.dockerignore, Makefile, README.md, config/default/kustomization.yaml, config/default/manager_auth_proxy_patch.yaml, config/default/manager_config_patch.yaml, config/manager/manager.yaml, config/manifests/kustomization.yaml, config/prometheus/monitor.yaml, config/rbac/auth_proxy_role_binding.yaml, config/rbac/auth_proxy_service.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role_binding.yaml, config/rbac/service_account.yaml, dataplane/.dockerignore, dataplane/Dockerfile, dataplane/Makefile, dataplane/ebpf/src/main.rs, pkg/vars/vars.go, tools/udp-test-server/.dockerignore, tools/udp-test-server/Dockerfile, tools/udp-test-server/src/main.rs
- chore: rename controller-manager to controlplane
- chore: cleanup the README.md
- chore: improve .dockerignore files throughout
- fix: udp test server ignore stream data
- fix: reduce spam from healthcheck peers
- chore: improve caching for rust image builds
- feat: add makefile directive to build dev cluster
=> chore: various cleanup

dataplane/api-server/build.rs, dataplane/xtask/build.rs
With Ubuntu 22.04, the latest version (installed via apt-get) of protobuf is `3.12.4`. With such a version, the dataplane build requires the flag `--experimental_allow_proto3_optional` to be successful. This PR introduces such a flag in both the api-server and xtask build targets.
=> chore: experimental proto3 flag

dataplane/api-server/src/backends.rs
With Rust 1.66 (https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#rust-166), `derive_partial_eq_without_eq` has been moved to nursery, meaning that it is enabled by default (https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#moves-and-deprecations).
=> chore: clippy derive_partial_eq_without_eq enabled

dataplane/Dockerfile, dataplane/ebpf/rust-toolchain.toml, dataplane/xtask/src/build_ebpf.rs
The 2023-01-11 nightly rust build [broke aya](https://github.com/aya-rs/aya/issues/490) and subsequently the build of the Blixt Dataplane.
Pinning the rust toolchain version to 2023-01-10 as a temporary fix.
=> fix: pin Rust nightly version to 2023-01-10

.vscode/settings.json, dataplane/ebpf/.vscode/settings.json, go.mod, go.sum
This PR contains the following chores:
- go.mod has been updated to remove the unused entry `github.com/moby/spdystream v0.2.0 // indirect`.
- a new `.vscode/settings.json` has been created in the root directory to enable rust-analyzer in the `dataplane/ebpf` sub-directory. Before that, it was impossible to navigate code under `dataplane/ebpf` in vscode.
=> Chores: go.mod and root `.vscode/settings.json`

README.md
The frequency of the code jam meeting is out of date, just removing it in favor of the link instead so this doesn't bitrot.
=> docs: update meetings in community section of README.md

controllers/gateway_controller_utils.go, test/integration/gateway_test.go
This adds the groundwork for allocating known IP addresses for `Gateways` when they are created.
This supports #96, but doesn't resolve it yet as this solution will be provided iteratively in multiple smaller PRs.
=> Static IPs for Gateways

.github/workflows/test.yaml, Makefile, controllers/gateway_controller_status.go, controllers/gateway_controller_test.go, controllers/gateway_controller_utils.go, test/conformance/gateway_conformance_test.go
This patch adds the initial scaffolding to start running the Gateway API conformance test suite on every PR.
This includes _some_ Gateway support related testing, but some tests are disabled for the moment as some are broken in upstream, and some specification simply isn't implemented yet here in Blixt.
This doesn't resolve, but it does support #95.
=> Initial GatewayClass/Gateway Conformance Setup

.github/workflows/test.yaml, Makefile, config/bpf-bytecode/kustomization.yaml, config/bpf-bytecode/tc-egress.yaml, config/bpf-bytecode/tc-ingress.yaml, config/bpfd-install/kustomization.yaml, config/bpfd-install/patch.yaml, config/bpfd/bpfd.yaml, config/bpfd/kustomization.yaml, config/tests/integration-bpfd/kustomization.yaml, dataplane/.cargo/config.toml, dataplane/Makefile, dataplane/api-server/src/backends.rs, dataplane/ebpf/.cargo/config.toml, dataplane/ebpf/Cargo.toml, dataplane/ebpf/src/main.rs, dataplane/loader/src/main.rs, test/integration/suite_test.go
This sets up the integration with [bpfd](bpfd.dev)
Additionally it adds a deployment scenario to the integration tests so that we run with and without bpfd.
To test it out locally 
```
1. Build Cluster: make build.cluster
2. Install bpfd: kubectl apply -k ./config/bpfd-install
3. Install Blixt with bpfd programs: kubectl apply -k ./config/bpfd
```
=> Bpfd integration

.github/workflows/test.yaml, config/samples/tcproute/server.yaml, config/tests/tcproute-rr/kustomization.yaml, config/tests/tcproute-rr/patch.yaml, config/tests/tcproute-rr/server.yaml, dataplane/api-server/src/backends.rs, dataplane/api-server/src/lib.rs, dataplane/api-server/src/server.rs, dataplane/common/src/lib.rs, dataplane/ebpf/src/egress/tcp.rs, dataplane/ebpf/src/ingress/tcp.rs, dataplane/ebpf/src/main.rs, dataplane/ebpf/src/utils.rs, dataplane/loader/src/main.rs, internal/dataplane/client/utils.go, test/integration/tcproute_test.go
Add support for round-robin load balancing for `TCPRoute`. This enables mutliple backend references in a UDPRoute object, with traffic being distributed to each backend in a round-robin fashion.
A new BPF map `TCP_CONNECTIONS` was introduced to help keep track of active TCP connections, with its key storing the clien <<ip:port>> identifier and the value storing the backend's <<ip:port>> along with the state of the connection.
Fixes #119 
Follow up items:
* modify `TCP_CONNECTIONS` to be more generic; get rid of `BLIXT_CONNTRACK` and refactor udp ingress and icmp egress to use the new generic map
=> tcproute: add support for round-robin load balancing

Makefile, README.md
Currently, our image repository (ghcr.io) is private. So users should build and load images themselves.
This PR modifies The usage part in README to add that information.
Fixes: #175
=> Modify README/usage to address the current situation

Dockerfile, Makefile, dataplane/Dockerfile, dataplane/Makefile
Add support for cross architeture Docker builds. Since Arch linux doesn't have an official image for arm64, switch to Debian for building the dataplane.
=> Add support for cross arch docker builds

config/dataplane/dataplane.yaml, dataplane/api-server/Cargo.toml, dataplane/api-server/src/lib.rs, test/integration/suite_test.go
Currently our dataplane server doesn't have health check, so we can't confirm whether the dataplane daemonset runs properly or not.
This PR introduce health check for gRPC to the dataplane server, and add liveness, readiness, and startup probe for the daemonset.
Fixes: #51
=> Dataplane: Add gRPC health check 

dataplane/ebpf/Cargo.lock, dataplane/ebpf/Cargo.toml, dataplane/ebpf/src/ingress/tcp.rs, dataplane/ebpf/src/ingress/udp.rs, dataplane/ebpf/src/utils.rs
udp and tcp ingress:
1. use `bpf_l4_csum_replace` `bpf_l3_csum_replace` to recalculate the checksums;
2. and `bpf_skb_store_bytes` to update dest ip and port;
Signed-off-by: tzssangglass <tzssangglass@gmail.com>
=> refactor: optimize TCP and UDP checksum handling with eBPF

Makefile
Currently the makefile fails to select the correct build platform for arm devices that return `aarch64` as the result for `uname -m`.
=> Fix: detect when hardware platform is aarch64

Makefile, build/Containerfile.dataplane, build/Containerfile.udp_server, tools/performance/Dockerfile
fix warnings when build images
```
1 warning found (use docker --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2)
```
and
```
=> WARN: LegacyKeyValueFormat: "LABEL key=value" should be used instead of legacy "LABEL key value" format (line 5)                                                                           0.0s
=> WARN: LegacyKeyValueFormat: "LABEL key=value" should be used instead of legacy "LABEL key value" format (line 6)                                                                           0.0s
=> WARN: LegacyKeyValueFormat: "LABEL key=value" should be used instead of legacy "LABEL key value" format (line 8)  
```
=> fix warnings when build images

build/Containerfile.dataplane
Fixes #291 
An even better solution is to update Aya and fix the references used. But I think we should copy `Cargo.lock` nonetheless during build time
=> fix: copy Cargo.lock when building dataplane

build/Containerfile.controlplane
The `make build.image.controlplane` command was failing due to incorrect file paths for `src`, `Cargo.toml`, and `Cargo.lock`. This PR updates the Dockerfile to reference the correct paths within the `controlplane` directory
To test this change:
1. Clone the repository.
2. Run `make build.image.controlplane`.  
The build should complete successfully without any errors.
=> fix: controlplane Dockerfile

Cargo.lock, dataplane/api-server/Cargo.toml, dataplane/api-server/tests/test_setup_tls.rs
This needed to be done manually due to breaking changes that occurred in [v0.13.0](https://github.com/rustls/rcgen/releases/tag/v0.13.0).
More context:
The `generate_simple_self_signed` used to be implemented this way prior to `0.13.0`:
```rust
pub fn generate_simple_self_signed(
subject_alt_names: impl Into<Vec<String>>,
) -> Result<Certificate, Error> {
Certificate::from_params(CertificateParams::new(subject_alt_names))
}
```
(link [here](https://github.com/rustls/rcgen/blob/1d2df16085eacf2fe9cd0f54dcb2ccc5980c9a8e/rcgen/src/lib.rs#L106))
But in `0.13.0` was updated to this, and now returns a `CertifiedKey` instead of just a `Certificate`:
```rust
pub fn generate_simple_self_signed(
subject_alt_names: impl Into<Vec<String>>,
) -> Result<CertifiedKey, Error> {
let key_pair = …
```
=> chore: update the rcgen dev dependency for the API server

controlplane/src/gateway_controller.rs, controlplane/src/main.rs, dataplane/api-server/src/netutils.rs
This PR fixes minor typos in controlplane logs and comment docs of dp components.
=> (fix): incorrect logs in controlplane

.gitignore, Cargo.lock, Cargo.toml, build/Containerfile.dataplane, controlplane/Cargo.toml, dataplane/api-server/Cargo.toml, dataplane/common/Cargo.toml, dataplane/loader/Cargo.toml, xtask/Cargo.toml, xtask/src/main.rs, xtask/src/run.rs
This PR attempts to add some distinctions between components that build on Linux and components that don't, mainly in service of MacOS development environments, as historically the entire development ecosystem and build system for Blixt has been Linux-only.
Also provided are some general fixes and improvements for building and testing.
=> chore: try to make contorlplane dev better

dataplane/api-server/src/lib.rs, xtask/src/run.rs
This PR
- adds debug and info logs to print out addresses & ports being used by data plane for gRPC health service.
- updates xtask command to run data plane with debug log level for `api_server`
- fixes incorrect xtask command name for controlplane (typo).
=> (feat): debug logs on data plane for health service addresses
